"use client";
import { ChangeEvent, DragEvent, useRef, useState } from "react";
type Phase = "idle" | "uploading" | "converting" | "done" | "error";
type Result = { id: string; downloadName: string; conversion: string };
const formats = ["application/pdf", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"];
function formatSize(bytes: number) { return new Intl.NumberFormat(undefined, { style: "unit", unit: "megabyte", maximumFractionDigits: 2 }).format(bytes / 1024 / 1024); }
export default function UploadCard() {
 const inputRef = useRef<HTMLInputElement>(null); const [file, setFile] = useState<File>(); const [phase, setPhase] = useState<Phase>("idle"); const [result, setResult] = useState<Result>(); const [error, setError] = useState("");
 const choose = (next?: File) => { setError(""); setResult(undefined); if (!next) return; if (!formats.includes(next.type) && !/\.(pdf|docx)$/i.test(next.name)) { setFile(undefined); setError("Choose a PDF or DOCX file."); return; } setFile(next); setPhase("idle"); };
 const submit = async () => { if (!file) return; setPhase("uploading"); setError(""); try { const data = new FormData(); data.set("file", file); setPhase("converting"); const response = await fetch("/api/convert", { method: "POST", body: data }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Conversion could not be completed."); setResult(body); setPhase("done"); } catch (cause) { setPhase("error"); setError(cause instanceof Error ? cause.message : "Conversion could not be completed."); } };
 const reset = () => { setFile(undefined); setResult(undefined); setError(""); setPhase("idle"); if (inputRef.current) inputRef.current.value = ""; };
 const drop = (event: DragEvent<HTMLDivElement>) => { event.preventDefault(); choose(event.dataTransfer.files[0]); };
 const conversion = file?.name.toLowerCase().endsWith(".pdf") ? "PDF ? Word (.docx)" : "Word (.docx) ? PDF";
 return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-8" aria-labelledby="upload-heading"><h2 id="upload-heading" className="sr-only">Upload a document</h2>{!file ? <div onDrop={drop} onDragOver={(e) => e.preventDefault()} className="rounded-xl border-2 border-dashed border-slate-300 bg-slate-50 px-5 py-12 text-center"><div className="mx-auto mb-4 grid h-12 w-12 place-items-center rounded-full bg-blue-100 text-xl text-blue-700">?</div><p className="font-semibold text-slate-800">Drag and drop a PDF or DOCX here</p><p className="mt-1 text-sm text-slate-500">or choose a file from your device</p><button type="button" onClick={() => inputRef.current?.click()} className="mt-6 rounded-lg bg-blue-600 px-5 py-2.5 font-semibold text-white shadow-sm hover:bg-blue-700">Choose file</button><input ref={inputRef} onChange={(e: ChangeEvent<HTMLInputElement>) => choose(e.target.files?.[0])} type="file" className="sr-only" accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" /></div> : <div><div className="flex flex-wrap items-center justify-between gap-4 rounded-xl bg-slate-50 p-4"><div><p className="max-w-xs truncate font-semibold text-slate-900">{file.name}</p><p className="mt-1 text-sm text-slate-500">{formatSize(file.size)} · {conversion}</p></div><button type="button" onClick={reset} disabled={phase === "uploading" || phase === "converting"} className="text-sm font-medium text-blue-700 hover:underline">Remove</button></div>{phase !== "done" && <button type="button" disabled={phase === "uploading" || phase === "converting"} onClick={submit} className="mt-5 w-full rounded-lg bg-blue-600 px-5 py-3 font-semibold text-white hover:bg-blue-700 disabled:cursor-wait disabled:bg-blue-400">{phase === "uploading" ? "Uploading…" : phase === "converting" ? "Converting…" : "Convert document"}</button>}{phase === "done" && result && <div className="mt-5 rounded-lg bg-emerald-50 p-4"><p className="font-semibold text-emerald-900">Conversion complete</p><a href={`/api/download/${result.id}`} className="mt-3 inline-block rounded-lg bg-blue-600 px-5 py-2.5 font-semibold text-white hover:bg-blue-700">Download {result.downloadName}</a><button type="button" onClick={reset} className="ml-4 text-sm font-medium text-blue-700 hover:underline">Convert another</button></div>}</div>}<p className="mt-4 min-h-5 text-sm text-red-700" role="status" aria-live="polite">{error}</p></section>;
}
